För att kunna köra inlärning med modifierad MNIST-kod är det nog lättast att lägga in kategorierna som nummer också i databasen. För att det ska vara lätt att mappa numren lägger jag in dem efter storleken på kategorierna.

In [105]:
import numpy as np
import sqlite3

In [46]:
conv = {0:lambda x: x.decode()} #Konvertern är för att filen är i unicode
categories = np.genfromtxt('../metadata/huvudgrupper.csv',  delimiter =";",dtype='U128',converters=conv)
print(categories[0])

['Likör' '3']

In [62]:
categories.T[1]

array(['3', '7', '28', '39', '6', '3', '33', '1', '9', '12', '23', '5',
       '31', '21', '18', '11', '16', '15', '5', '10', '24', '11', '4', '3',
       '1', '6', '3', '11', '51', '6', '15', '13', '94', '19', '11', '86',
       '22', '2', '2', '29', '8', '22', '25', '8', '14', '79', '8', '14',
       '12', '3', '11', '7', '4', '60', '22', '7', '15', '9', '31', '1',
       '1', '4', '6', '1', '12', '13', '3', '11', '3', '5', '4', '47',
       '80', '4', '39', '6', '42', '8', '2', '68', '3', '33', '18', '3',
       '3', '2', '26', '14', '9', '2', '7', '13', '28', '3', '5', '6', '2',
       '3', '25', '4', '1', '10', '9', '17', '25', '46', '42', '4', '127',
       '7', '55', '69', '2', '1', '2', '15', '1', '15'],
      dtype='<U128')

Eftersom dtype för categories är unicode går det inte att sortera categories direkt. Därför måste jag skapa en ny array "antal" som är index från 0 till antal kategorier i första kolumnen och antalet i varje kategori i den andra kolumnen.

Hade varit fint med ett sätt att slippa detta...

In [131]:
langd = len(categories.T[1])
antal = np.array([range(langd),categories.T[1]],dtype=int).T #Obs syntaxen med [] för att skapa arrayen
print(antal)

[[  0   3]
 [  1   7]
 [  2  28]
 [  3  39]
 [  4   6]
 [  5   3]
 [  6  33]
 [  7   1]
 [  8   9]
 [  9  12]
 [ 10  23]
 [ 11   5]
 [ 12  31]
 [ 13  21]
 [ 14  18]
 [ 15  11]
 [ 16  16]
 [ 17  15]
 [ 18   5]
 [ 19  10]
 [ 20  24]
 [ 21  11]
 [ 22   4]
 [ 23   3]
 [ 24   1]
 [ 25   6]
 [ 26   3]
 [ 27  11]
 [ 28  51]
 [ 29   6]
 [ 30  15]
 [ 31  13]
 [ 32  94]
 [ 33  19]
 [ 34  11]
 [ 35  86]
 [ 36  22]
 [ 37   2]
 [ 38   2]
 [ 39  29]
 [ 40   8]
 [ 41  22]
 [ 42  25]
 [ 43   8]
 [ 44  14]
 [ 45  79]
 [ 46   8]
 [ 47  14]
 [ 48  12]
 [ 49   3]
 [ 50  11]
 [ 51   7]
 [ 52   4]
 [ 53  60]
 [ 54  22]
 [ 55   7]
 [ 56  15]
 [ 57   9]
 [ 58  31]
 [ 59   1]
 [ 60   1]
 [ 61   4]
 [ 62   6]
 [ 63   1]
 [ 64  12]
 [ 65  13]
 [ 66   3]
 [ 67  11]
 [ 68   3]
 [ 69   5]
 [ 70   4]
 [ 71  47]
 [ 72  80]
 [ 73   4]
 [ 74  39]
 [ 75   6]
 [ 76  42]
 [ 77   8]
 [ 78   2]
 [ 79  68]
 [ 80   3]
 [ 81  33]
 [ 82  18]
 [ 83   3]
 [ 84   3]
 [ 85   2]
 [ 86  26]
 [ 87  14]
 [ 88   9]
 [ 89   2]
 [ 90   7]
 [ 91  13]
 [ 92  28]
 [ 93   3]
 [ 94   5]
 [ 95   6]
 [ 96   2]
 [ 97   3]
 [ 98  25]
 [ 99   4]
 [100   1]
 [101  10]
 [102   9]
 [103  17]
 [104  25]
 [105  46]
 [106  42]
 [107   4]
 [108 127]
 [109   7]
 [110  55]
 [111  69]
 [112   2]
 [113   1]
 [114   2]
 [115  15]
 [116   1]
 [117  15]]

In [132]:
#Sortering efter kolumn en med antal, med "fancy indexing"
antal = antal[antal[:,1].argsort()]

#Få arrayen i rätt ordning, eftersom man inte verkar kunna definiera omvänd sorteringsordning
#https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.flipud.html
antal = np.flipud(antal)

antal.T[0]

array([108,  32,  35,  72,  45, 111,  79,  53, 110,  28,  71, 105,  76,
       106,  74,   3,   6,  81,  58,  12,  39,   2,  92,  86,  98, 104,
        42,  20,  10,  54,  41,  36,  13,  33,  82,  14, 103,  16,  56,
        30,  17, 117, 115,  44,  87,  47,  91,  31,  65,  48,   9,  64,
        50,  34,  67,  15,  21,  27,  19, 101,  57,  88, 102,   8,  40,
        46,  77,  43,  51,  90,  55, 109,   1,  95,  29,  75,  25,  62,
         4,  18,  11,  94,  69,  52, 107,  61,  99,  70,  22,  73,   5,
        23,   0,  66,  83,  97,  68,  93,  80,  49,  26,  84, 114, 112,
        37,  78,  89,  38,  96,  85, 113,  24,   7,  63,  60,  59, 100, 116])

Den sorterade arrayen används sen som index till arrayen av kategorier...

Kan man verkligen inte fixa det här på ett bättre sätt?

In [108]:
ordered_categories = categories[antal.T[0]]
ordered_categories

array([['Kött färskt fryst tillagat', '127'],
       ['Grönsaker', '94'],
       ['Bullar kakor tårtor mm', '86'],
       ['Köttprodukter kötträtter', '80'],
       ['Sås dressing majonnäs', '79'],
       ['Fisk o skaldjursprodukter o rätter', '69'],
       ['Fisk färsk fryst kokt', '68'],
       ['Korv', '60'],
       ['Grönsaks- rotfrukts- baljväxträtter och produkter', '55'],
       ['Baljväxter (bönor, linser och ärter)', '51'],
       ['Soppa mat', '47'],
       ['Pizza paj pirog färdig smörgås', '46'],
       ['Mjukt bröd', '42'],
       ['Frukt färsk fryst', '42'],
       ['Hård matfettsblandning', '39'],
       ['Fågel', '39'],
       ['Potatisprodukter o rätter', '33'],
       ['Inälvor och organ', '33'],
       ['Potatis', '31'],
       ['Efterrätter', '31'],
       ['Mjöl stärkelse kli', '29'],
       ['Flingor - frukostflingor', '28'],
       ['Hårt bröd', '28'],
       ['Söta soppor kräm o efterrättssås', '26'],
       ['Kött processat', '25'],
       ['Ris risnudlar', '25'],
       ['Glass', '25'],
       ['Bär färska frysta', '24'],
       ['Grädde creme fraiche', '23'],
       ['Nötter frön', '22'],
       ['Rotfrukter', '22'],
       ['Fruktjuice mm', '22'],
       ['Pasta', '21'],
       ['Saft läsk cider u alkohol', '19'],
       ['Sylt marmelad gelé äppelmos o dyl', '18'],
       ['Buljong', '18'],
       ['Frukt o bär konserverade', '17'],
       ['Gröt', '16'],
       ['Färskost o kvarg', '15'],
       ['Olja', '15'],
       ['Vatten mineralvatten', '15'],
       ['Inälvor organ produkter o rätter', '15'],
       ['Godis som innehåller choklad', '15'],
       ['Matgryn', '14'],
       ['Skaldjur bläckfisk färsk fryst kokt', '14'],
       ['Frukt o bär torkade', '14'],
       ['Vegetabiliska produkter och mjölkersättning', '13'],
       ['Pannkakor, våfflor, crêpes', '13'],
       ['Fisk rökt', '13'],
       ['Pastarätter', '12'],
       ['Smaksatt fil yoghurt', '12'],
       ['Välling', '12'],
       ['Mjölk', '11'],
       ['Chips popcorn o dyl', '11'],
       ['Senap ketchup HP-sås soja *smaksättare*', '11'],
       ['Hård ost m.m.', '11'],
       ['Godis ej choklad', '11'],
       ['Naturell fil yoghurt', '11'],
       ['Sallad blandad mat', '10'],
       ['Vin', '10'],
       ['Svamp', '9'],
       ['Ägg', '9'],
       ['Grönsaksblandningar med rotfrukter och eller baljväxter', '9'],
       ['Korvrätter', '9'],
       ['Blodprodukter o rätter', '8'],
       ['Smältost', '8'],
       ['Dessertost', '8'],
       ['Kost- o näringspreparat', '8'],
       ['Choklad', '7'],
       ['Starksprit', '7'],
       ['Flytande matfettsblandning', '7'],
       ['Fisk stekt ej panerad', '7'],
       ['Smörgåskex', '7'],
       ['Mesvaror', '6'],
       ['Skaldjur bläckfisk konserverad', '6'],
       ['Äggprodukter o rätter', '6'],
       ['Majonnässallad röror', '6'],
       ['Rom, kaviar', '6'],
       ['Socker sirap honung', '6'],
       ['Kaffe', '5'],
       ['Fågelprodukter o rätter', '5'],
       ['Hamburgare med  bröd (kött, fisk, fågel, vegetarisk)', '5'],
       ['Mjölkdryck chokladdryck milkshake smothie m yoghurt', '5'],
       ['Lightdrycker u energi', '4'],
       ['Salt', '4'],
       ['Öl', '4'],
       ['Övrigt fett (ister, talg, kokosfett)', '4'],
       ['Övriga sötade drycker vattenchoklad', '4'],
       ['Te', '4'],
       ['Grönsaksjuice rotfruktsjuice', '4'],
       ['Övrigt', '3'],
       ['Sojaprotein veteprotein Quorn produkter och rätter', '3'],
       ['Jäst bakpulver', '3'],
       ['Sylta', '3'],
       ['Osträtter', '3'],
       ['Ost med vegetabilskt fett', '3'],
       ['Deg och gräddade skal och bottnar', '3'],
       ['Soja-  veteprotein o quorn', '3'],
       ['Smör', '3'],
       ['Likör', '3'],
       ['Ättika vinäger', '3'],
       ['Cider alkoläsk drink', '3'],
       ['Riskakor', '2'],
       ['Frukt o bär', '2'],
       ['Frukt o nötblandningar bars', '2'],
       ['Gelatin agar agar', '2'],
       ['Sportdrycker energidrycker', '2'],
       ['Kakaoprodukter', '2'],
       ['Tuggummi', '2'],
       ['Blodmat', '2'],
       ['Sockerfritt godis', '1'],
       ['Sötningsmedel', '1'],
       ['Kryddor', '1'],
       ['Algprodukter', '1'],
       ['Risrätter', '1'],
       ['Tacoskal', '1'],
       [ 'Övrigt animaliskt *kött*, grodlår, sniglar, säl - färskt, fryst, tillagat',
        '1'],
       ['Dryck', '1']],
      dtype='<U128')

## Läs ner i databasen

Kolla om tabellen finns, och läs sen ner kategorinumren i databasen

In [107]:
conn = sqlite3.connect('../livs.db')  # Create db and establish connection
conn.row_factory = sqlite3.Row
curs = conn.cursor()

columnObject = []

#Kolla om Huvudgrupp-kolumnen redan finns, annars lägg till den        
for row in conn.execute('PRAGMA table_info (livs);'):
    columnObject.append(row)
columns = np.array(columnObject)
newColumn = 'Huvudgrupp_n'
addColumn = True
for row in columns:
    print (row)
    if newColumn == row[1]:
        addColumn = False
        print (addColumn, newColumn)
if addColumn:
    #Man får se upp extra noga med kolumntypen, för den går inte att ändra i efterhand i sqlite...
    conn.execute('ALTER TABLE livs ADD COLUMN Huvudgrupp_n INTEGER;')
    conn.commit()

conn.close()

[0 'Livsmedelsnamn' 'TEXT' 0 None 0]
[1 'Livsmedelsnummer' 'TEXT' 0 None 0]
[2 'Energi_kcal' 'REAL' 0 None 0]
[3 'Energi_kJ' 'REAL' 0 None 0]
[4 'Kolhydrater_g' 'REAL' 0 None 0]
[5 'Fett_g' 'REAL' 0 None 0]
[6 'Protein_g' 'REAL' 0 None 0]
[7 'Fibrer_g' 'REAL' 0 None 0]
[8 'Vatten_g' 'REAL' 0 None 0]
[9 'Alkohol_g' 'REAL' 0 None 0]
[10 'Aska_g' 'REAL' 0 None 0]
[11 'Monosackarider_g' 'REAL' 0 None 0]
[12 'Disackarider_g' 'REAL' 0 None 0]
[13 'Sackaros_g' 'REAL' 0 None 0]
[14 'Fullkorn_totalt_g' 'REAL' 0 None 0]
[15 'Sockerarter_g' 'REAL' 0 None 0]
[16 'Summa_mattade_fettsyror_g' 'REAL' 0 None 0]
[17 'Fettsyra_4_0_10_0_g' 'REAL' 0 None 0]
[18 'Fettsyra_12_0_g' 'REAL' 0 None 0]
[19 'Fettsyra_14_0_g' 'REAL' 0 None 0]
[20 'Fettsyra_16_0_g' 'REAL' 0 None 0]
[21 'Fettsyra_18_0_g' 'REAL' 0 None 0]
[22 'Fettsyra_20_0_g' 'REAL' 0 None 0]
[23 'Summa_enkelomattade_fettsyror_g' 'REAL' 0 None 0]
[24 'Fettsyra_16_1_g' 'REAL' 0 None 0]
[25 'Fettsyra_18_1_g' 'REAL' 0 None 0]
[26 'Summa_fleromattade_fettsyror_g' 'REAL' 0 None 0]
[27 'Fettsyra_18_2_g' 'REAL' 0 None 0]
[28 'Fettsyra_18_3_g' 'REAL' 0 None 0]
[29 'Fettsyra_20_4_g' 'REAL' 0 None 0]
[30 'EPA_Fettsyra_20_5_g' 'REAL' 0 None 0]
[31 'DPA_Fettsyra_22_5_g' 'REAL' 0 None 0]
[32 'DHA_Fettsyra_22_6_g' 'REAL' 0 None 0]
[33 'Kolesterol_mg' 'REAL' 0 None 0]
[34 'Retinol_mikrog' 'REAL' 0 None 0]
[35 'Vitamin_A_mikrog' 'REAL' 0 None 0]
[36 'beta_Karoten_mikrog' 'REAL' 0 None 0]
[37 'Vitamin_D_mikrog' 'REAL' 0 None 0]
[38 'Vitamin_E_mg' 'REAL' 0 None 0]
[39 'Vitamin_K_mikrog' 'REAL' 0 None 0]
[40 'Tiamin_mg' 'REAL' 0 None 0]
[41 'Riboflavin_mg' 'REAL' 0 None 0]
[42 'Vitamin_C_mg' 'REAL' 0 None 0]
[43 'Niacin_mg' 'REAL' 0 None 0]
[44 'Niacinekvivalenter_mg' 'REAL' 0 None 0]
[45 'Vitamin_B6_mg' 'REAL' 0 None 0]
[46 'Vitamin_B12_mikrog' 'REAL' 0 None 0]
[47 'Folat_mikrog' 'REAL' 0 None 0]
[48 'Fosfor_mg' 'REAL' 0 None 0]
[49 'Jod_mikrog' 'REAL' 0 None 0]
[50 'Jarn_mg' 'REAL' 0 None 0]
[51 'Kalcium_mg' 'REAL' 0 None 0]
[52 'Kalium_mg' 'REAL' 0 None 0]
[53 'Magnesium_mg' 'REAL' 0 None 0]
[54 'Natrium_mg' 'REAL' 0 None 0]
[55 'Salt_g' 'REAL' 0 None 0]
[56 'Selen_mikrog' 'REAL' 0 None 0]
[57 'Zink_mg' '' 0 None 0]
[58 'Avfall_skal_etc' 'REAL' 0 None 0]
[59 'Kluster' 'REAL' 0 None 0]
[60 'Huvudgrupp' 'TEXT' 0 None 0]
[61 'Huvudgrupp_n' 'INTEGER' 0 None 0]
False Huvudgrupp_n

In [128]:
conn = sqlite3.connect('../livs.db')  # Create db and establish connection
conn.row_factory = sqlite3.Row
curs = conn.cursor()

#print (len(ordered_categories))

i = 0
for row in ordered_categories:
    #print(row[1], row[0],i)
    #print (row[0].dtype)
    sql = 'UPDATE livs SET Huvudgrupp_n = '+str(i)+' WHERE Huvudgrupp = "'+row[0]+'";'
    print(sql)
    curs.execute(sql) #Kommentera bort denna vid debug...
    conn.commit()
    i+=1

conn.close()

UPDATE livs SET Huvudgrupp_n = 0 WHERE Huvudgrupp = "Kött färskt fryst tillagat";
UPDATE livs SET Huvudgrupp_n = 1 WHERE Huvudgrupp = "Grönsaker";
UPDATE livs SET Huvudgrupp_n = 2 WHERE Huvudgrupp = "Bullar kakor tårtor mm";
UPDATE livs SET Huvudgrupp_n = 3 WHERE Huvudgrupp = "Köttprodukter kötträtter";
UPDATE livs SET Huvudgrupp_n = 4 WHERE Huvudgrupp = "Sås dressing majonnäs";
UPDATE livs SET Huvudgrupp_n = 5 WHERE Huvudgrupp = "Fisk o skaldjursprodukter o rätter";
UPDATE livs SET Huvudgrupp_n = 6 WHERE Huvudgrupp = "Fisk färsk fryst kokt";
UPDATE livs SET Huvudgrupp_n = 7 WHERE Huvudgrupp = "Korv";
UPDATE livs SET Huvudgrupp_n = 8 WHERE Huvudgrupp = "Grönsaks- rotfrukts- baljväxträtter och produkter";
UPDATE livs SET Huvudgrupp_n = 9 WHERE Huvudgrupp = "Baljväxter (bönor, linser och ärter)";
UPDATE livs SET Huvudgrupp_n = 10 WHERE Huvudgrupp = "Soppa mat";
UPDATE livs SET Huvudgrupp_n = 11 WHERE Huvudgrupp = "Pizza paj pirog färdig smörgås";
UPDATE livs SET Huvudgrupp_n = 12 WHERE Huvudgrupp = "Mjukt bröd";
UPDATE livs SET Huvudgrupp_n = 13 WHERE Huvudgrupp = "Frukt färsk fryst";
UPDATE livs SET Huvudgrupp_n = 14 WHERE Huvudgrupp = "Hård matfettsblandning";
UPDATE livs SET Huvudgrupp_n = 15 WHERE Huvudgrupp = "Fågel";
UPDATE livs SET Huvudgrupp_n = 16 WHERE Huvudgrupp = "Potatisprodukter o rätter";
UPDATE livs SET Huvudgrupp_n = 17 WHERE Huvudgrupp = "Inälvor och organ";
UPDATE livs SET Huvudgrupp_n = 18 WHERE Huvudgrupp = "Potatis";
UPDATE livs SET Huvudgrupp_n = 19 WHERE Huvudgrupp = "Efterrätter";
UPDATE livs SET Huvudgrupp_n = 20 WHERE Huvudgrupp = "Mjöl stärkelse kli";
UPDATE livs SET Huvudgrupp_n = 21 WHERE Huvudgrupp = "Flingor - frukostflingor";
UPDATE livs SET Huvudgrupp_n = 22 WHERE Huvudgrupp = "Hårt bröd";
UPDATE livs SET Huvudgrupp_n = 23 WHERE Huvudgrupp = "Söta soppor kräm o efterrättssås";
UPDATE livs SET Huvudgrupp_n = 24 WHERE Huvudgrupp = "Kött processat";
UPDATE livs SET Huvudgrupp_n = 25 WHERE Huvudgrupp = "Ris risnudlar";
UPDATE livs SET Huvudgrupp_n = 26 WHERE Huvudgrupp = "Glass";
UPDATE livs SET Huvudgrupp_n = 27 WHERE Huvudgrupp = "Bär färska frysta";
UPDATE livs SET Huvudgrupp_n = 28 WHERE Huvudgrupp = "Grädde creme fraiche";
UPDATE livs SET Huvudgrupp_n = 29 WHERE Huvudgrupp = "Nötter frön";
UPDATE livs SET Huvudgrupp_n = 30 WHERE Huvudgrupp = "Rotfrukter";
UPDATE livs SET Huvudgrupp_n = 31 WHERE Huvudgrupp = "Fruktjuice mm";
UPDATE livs SET Huvudgrupp_n = 32 WHERE Huvudgrupp = "Pasta";
UPDATE livs SET Huvudgrupp_n = 33 WHERE Huvudgrupp = "Saft läsk cider u alkohol";
UPDATE livs SET Huvudgrupp_n = 34 WHERE Huvudgrupp = "Sylt marmelad gelé äppelmos o dyl";
UPDATE livs SET Huvudgrupp_n = 35 WHERE Huvudgrupp = "Buljong";
UPDATE livs SET Huvudgrupp_n = 36 WHERE Huvudgrupp = "Frukt o bär konserverade";
UPDATE livs SET Huvudgrupp_n = 37 WHERE Huvudgrupp = "Gröt";
UPDATE livs SET Huvudgrupp_n = 38 WHERE Huvudgrupp = "Färskost o kvarg";
UPDATE livs SET Huvudgrupp_n = 39 WHERE Huvudgrupp = "Olja";
UPDATE livs SET Huvudgrupp_n = 40 WHERE Huvudgrupp = "Vatten mineralvatten";
UPDATE livs SET Huvudgrupp_n = 41 WHERE Huvudgrupp = "Inälvor organ produkter o rätter";
UPDATE livs SET Huvudgrupp_n = 42 WHERE Huvudgrupp = "Godis som innehåller choklad";
UPDATE livs SET Huvudgrupp_n = 43 WHERE Huvudgrupp = "Matgryn";
UPDATE livs SET Huvudgrupp_n = 44 WHERE Huvudgrupp = "Skaldjur bläckfisk färsk fryst kokt";
UPDATE livs SET Huvudgrupp_n = 45 WHERE Huvudgrupp = "Frukt o bär torkade";
UPDATE livs SET Huvudgrupp_n = 46 WHERE Huvudgrupp = "Vegetabiliska produkter och mjölkersättning";
UPDATE livs SET Huvudgrupp_n = 47 WHERE Huvudgrupp = "Pannkakor, våfflor, crêpes";
UPDATE livs SET Huvudgrupp_n = 48 WHERE Huvudgrupp = "Fisk rökt";
UPDATE livs SET Huvudgrupp_n = 49 WHERE Huvudgrupp = "Pastarätter";
UPDATE livs SET Huvudgrupp_n = 50 WHERE Huvudgrupp = "Smaksatt fil yoghurt";
UPDATE livs SET Huvudgrupp_n = 51 WHERE Huvudgrupp = "Välling";
UPDATE livs SET Huvudgrupp_n = 52 WHERE Huvudgrupp = "Mjölk";
UPDATE livs SET Huvudgrupp_n = 53 WHERE Huvudgrupp = "Chips popcorn o dyl";
UPDATE livs SET Huvudgrupp_n = 54 WHERE Huvudgrupp = "Senap ketchup HP-sås soja *smaksättare*";
UPDATE livs SET Huvudgrupp_n = 55 WHERE Huvudgrupp = "Hård ost m.m.";
UPDATE livs SET Huvudgrupp_n = 56 WHERE Huvudgrupp = "Godis ej choklad";
UPDATE livs SET Huvudgrupp_n = 57 WHERE Huvudgrupp = "Naturell fil yoghurt";
UPDATE livs SET Huvudgrupp_n = 58 WHERE Huvudgrupp = "Sallad blandad mat";
UPDATE livs SET Huvudgrupp_n = 59 WHERE Huvudgrupp = "Vin";
UPDATE livs SET Huvudgrupp_n = 60 WHERE Huvudgrupp = "Svamp";
UPDATE livs SET Huvudgrupp_n = 61 WHERE Huvudgrupp = "Ägg";
UPDATE livs SET Huvudgrupp_n = 62 WHERE Huvudgrupp = "Grönsaksblandningar med rotfrukter och eller baljväxter";
UPDATE livs SET Huvudgrupp_n = 63 WHERE Huvudgrupp = "Korvrätter";
UPDATE livs SET Huvudgrupp_n = 64 WHERE Huvudgrupp = "Blodprodukter o rätter";
UPDATE livs SET Huvudgrupp_n = 65 WHERE Huvudgrupp = "Smältost";
UPDATE livs SET Huvudgrupp_n = 66 WHERE Huvudgrupp = "Dessertost";
UPDATE livs SET Huvudgrupp_n = 67 WHERE Huvudgrupp = "Kost- o näringspreparat";
UPDATE livs SET Huvudgrupp_n = 68 WHERE Huvudgrupp = "Choklad";
UPDATE livs SET Huvudgrupp_n = 69 WHERE Huvudgrupp = "Starksprit";
UPDATE livs SET Huvudgrupp_n = 70 WHERE Huvudgrupp = "Flytande matfettsblandning";
UPDATE livs SET Huvudgrupp_n = 71 WHERE Huvudgrupp = "Fisk stekt ej panerad";
UPDATE livs SET Huvudgrupp_n = 72 WHERE Huvudgrupp = "Smörgåskex";
UPDATE livs SET Huvudgrupp_n = 73 WHERE Huvudgrupp = "Mesvaror";
UPDATE livs SET Huvudgrupp_n = 74 WHERE Huvudgrupp = "Skaldjur bläckfisk konserverad";
UPDATE livs SET Huvudgrupp_n = 75 WHERE Huvudgrupp = "Äggprodukter o rätter";
UPDATE livs SET Huvudgrupp_n = 76 WHERE Huvudgrupp = "Majonnässallad röror";
UPDATE livs SET Huvudgrupp_n = 77 WHERE Huvudgrupp = "Rom, kaviar";
UPDATE livs SET Huvudgrupp_n = 78 WHERE Huvudgrupp = "Socker sirap honung";
UPDATE livs SET Huvudgrupp_n = 79 WHERE Huvudgrupp = "Kaffe";
UPDATE livs SET Huvudgrupp_n = 80 WHERE Huvudgrupp = "Fågelprodukter o rätter";
UPDATE livs SET Huvudgrupp_n = 81 WHERE Huvudgrupp = "Hamburgare med  bröd (kött, fisk, fågel, vegetarisk)";
UPDATE livs SET Huvudgrupp_n = 82 WHERE Huvudgrupp = "Mjölkdryck chokladdryck milkshake smothie m yoghurt";
UPDATE livs SET Huvudgrupp_n = 83 WHERE Huvudgrupp = "Lightdrycker u energi";
UPDATE livs SET Huvudgrupp_n = 84 WHERE Huvudgrupp = "Salt";
UPDATE livs SET Huvudgrupp_n = 85 WHERE Huvudgrupp = "Öl";
UPDATE livs SET Huvudgrupp_n = 86 WHERE Huvudgrupp = "Övrigt fett (ister, talg, kokosfett)";
UPDATE livs SET Huvudgrupp_n = 87 WHERE Huvudgrupp = "Övriga sötade drycker vattenchoklad";
UPDATE livs SET Huvudgrupp_n = 88 WHERE Huvudgrupp = "Te";
UPDATE livs SET Huvudgrupp_n = 89 WHERE Huvudgrupp = "Grönsaksjuice rotfruktsjuice";
UPDATE livs SET Huvudgrupp_n = 90 WHERE Huvudgrupp = "Övrigt";
UPDATE livs SET Huvudgrupp_n = 91 WHERE Huvudgrupp = "Sojaprotein veteprotein Quorn produkter och rätter";
UPDATE livs SET Huvudgrupp_n = 92 WHERE Huvudgrupp = "Jäst bakpulver";
UPDATE livs SET Huvudgrupp_n = 93 WHERE Huvudgrupp = "Sylta";
UPDATE livs SET Huvudgrupp_n = 94 WHERE Huvudgrupp = "Osträtter";
UPDATE livs SET Huvudgrupp_n = 95 WHERE Huvudgrupp = "Ost med vegetabilskt fett";
UPDATE livs SET Huvudgrupp_n = 96 WHERE Huvudgrupp = "Deg och gräddade skal och bottnar";
UPDATE livs SET Huvudgrupp_n = 97 WHERE Huvudgrupp = "Soja-  veteprotein o quorn";
UPDATE livs SET Huvudgrupp_n = 98 WHERE Huvudgrupp = "Smör";
UPDATE livs SET Huvudgrupp_n = 99 WHERE Huvudgrupp = "Likör";
UPDATE livs SET Huvudgrupp_n = 100 WHERE Huvudgrupp = "Ättika vinäger";
UPDATE livs SET Huvudgrupp_n = 101 WHERE Huvudgrupp = "Cider alkoläsk drink";
UPDATE livs SET Huvudgrupp_n = 102 WHERE Huvudgrupp = "Riskakor";
UPDATE livs SET Huvudgrupp_n = 103 WHERE Huvudgrupp = "Frukt o bär";
UPDATE livs SET Huvudgrupp_n = 104 WHERE Huvudgrupp = "Frukt o nötblandningar bars";
UPDATE livs SET Huvudgrupp_n = 105 WHERE Huvudgrupp = "Gelatin agar agar";
UPDATE livs SET Huvudgrupp_n = 106 WHERE Huvudgrupp = "Sportdrycker energidrycker";
UPDATE livs SET Huvudgrupp_n = 107 WHERE Huvudgrupp = "Kakaoprodukter";
UPDATE livs SET Huvudgrupp_n = 108 WHERE Huvudgrupp = "Tuggummi";
UPDATE livs SET Huvudgrupp_n = 109 WHERE Huvudgrupp = "Blodmat";
UPDATE livs SET Huvudgrupp_n = 110 WHERE Huvudgrupp = "Sockerfritt godis";
UPDATE livs SET Huvudgrupp_n = 111 WHERE Huvudgrupp = "Sötningsmedel";
UPDATE livs SET Huvudgrupp_n = 112 WHERE Huvudgrupp = "Kryddor";
UPDATE livs SET Huvudgrupp_n = 113 WHERE Huvudgrupp = "Algprodukter";
UPDATE livs SET Huvudgrupp_n = 114 WHERE Huvudgrupp = "Risrätter";
UPDATE livs SET Huvudgrupp_n = 115 WHERE Huvudgrupp = "Tacoskal";
UPDATE livs SET Huvudgrupp_n = 116 WHERE Huvudgrupp = "Övrigt animaliskt *kött*, grodlår, sniglar, säl - färskt, fryst, tillagat";
UPDATE livs SET Huvudgrupp_n = 117 WHERE Huvudgrupp = "Dryck";